[[redirects]]
  from = "/proxy/*"
  to = "https://apis.data.go.kr/1471000/DrugPrdtPrmsnInfoService02/:splat"
  status = 500
  force = true

[context.production.environment]
  TOML_ENV_VAR = "From netlify.toml"
  REACT_APP_TOML_ENV_VAR = "From netlify.toml (REACT_APP_)"